INSERT INTO sil.doctors (id,nombre,especialidad,ci,telefono,email,registro,estado,establecimiento_id,deleted_at,created_at,updated_at) VALUES
	 (2,'Dra. Ana Gomez','Pediatria','87654321','555-5678','ana@gmail.com','REG-002','ACTIVO',1,NULL,'2025-12-13 06:38:37','2025-12-13 06:38:37'),
	 (3,'CARLOS ALBERTO LUCANA CHAMBI','ANATOMIA PATOLOGICA (HISTOPATOLOGIA)                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (4,'XIMENA CORTEZ MENDOZA','ANATOMIA PATOLOGICA (HISTOPATOLOGIA)                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (6,'ANGELICA ROSALES ALVAREZ','ANATOMIA PATOLOGICA(CITOLOGIA CERVICAL)                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (7,'MARIO TARQUI CHOQUE','ANATOMIA PATOLOGICA(CITOLOGIA CERVICAL)                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (8,'SUSANA DURAN RAMIREZ','ANATOMIA PATOLOGICA(CITOLOGIA CERVICAL)                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (9,'CARLOS ALBERTO LUCANA CHAMBI','ANATOMIA PATOLOGICA(CITOLOGIA CERVICAL)                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (10,'XIMENA CORTEZ MENDOZA','ANATOMIA PATOLOGICA(CITOLOGIA CERVICAL)                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (11,'ZACARIAS VILLARROEL VEGA','ANATOMIA PATOLOGICA(CITOLOGIA CERVICAL)                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (13,'PATRICIA VELA AVILA','ANESTESIOLOGIA COREA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (14,'WILMA VASQUEZ ROMAN','ANESTESIOLOGIA COREA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (15,'JOSUE CAHUANA LIZIDRO','ANESTESIOLOGIA COREA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (16,'JOSE VERDIGUEZ SANJINEZ','ANESTESIOLOGIA COREA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (17,'YASMIN ALISON GIL FUENTES','ANESTESIOLOGIA COREA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (18,'XIMENA KAREN DAGA SEMPERTEGUI','ANESTESIOLOGIA COREA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (19,'ERODITA GABRIEL CONDORI','ANESTESIOLOGIA COREA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (21,'MILY QUENA RIOS','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (22,'GRISEL H. FLORES MACKAY','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (23,'JIMENA CARMEN LINO OJEDA','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (24,'GUISELA GILKA DORADO ALANES','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (25,'PATRICIA CARACILA CHOQUE','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (26,'FERNANDO SERGIO LUCANA CAYOJA','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (27,'CARLOS RODRIGUEZ HERRERA','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (28,'JOEL SANCHEZ MOSCOSO','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (29,'ROGER URQUIZO LOPEZ','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (30,'MIRIAN JEANNETTE NUÑEZ BARRERO','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (31,'JUAN JOSE DORADO BARRIGA','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (32,'JOSE VERDIGUEZ SANJINEZ','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (33,'NOEMY BARRIONUEVO QUIROZ','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (34,'OSCAR DORADO MARISCAL','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (35,'ROGER ZAMBRANA RUIZ','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (36,'WILMA VASQUEZ ROMAN','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (37,'REMBERTO RIVERAS CADENA','ANESTESIOLOGIA HG                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (39,'MARIELA MAMANI CHAMBI','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (40,'CE - CARDIOLOGIA                                                                                    ','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (41,'MARCOS RAFAEL LOPEZ ALCOCER','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (42,'JUAN HUGO MUJICA NINAJA','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (43,'CARMEN ROXANA HONORIO QUISPE','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (44,'CE - CIRUGIA GENERAL                                                                                ','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (45,'MADAI SOTO ROJAS','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (46,'HENRY JOSE CORRALES LOPEZ','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (47,'OSCAR JAVIER FELIPEZ AGUILAR','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (48,'RODOLFO ROLANDO ESTEVEZ HURACHI','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (49,'ABZALON LORGIO LUCAS CHOQUE','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (50,'MARCO ANTONIO G. HURTADO AVILES','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (51,'DAVID TORREZ LOPEZ','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (52,'NELSON MENA CABALLERO','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (53,'JUAN VICTOR IQUISE ILACIO','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (54,'MICHAEL CALLAPA ZAMBRANA','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (55,'FABELA HERRERA HEREDIA','ANTICONCEPCIÓN                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (57,'MARIELA MAMANI CHAMBI','CE - ENDOCRINOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (58,'WALDO AYALA MONTAÑO','CE - ENDOCRINOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (59,'CHOQUE ERICK ARMANDO CAHUANA','CE - ENDOCRINOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (60,'GUISELA WENDY NUÑEZ CORDOVA','CE - ENDOCRINOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (61,'JUAN DOMINGO MAMANI HUARACHI','CE - ENDOCRINOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (63,'KAREN MELVA CHURATA MIRONES','CE - GASTROENTEROLOGIA                                                                              ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (64,'EDSON JAVIER CHUNGARA MURUCHI','CE - GASTROENTEROLOGIA                                                                              ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (66,'ERIK MENECES HIDALGO','CE - HEMATOLOGIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (67,'LOURDEZ MAGNE APAZA','CE - HEMATOLOGIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (68,'VERONICA TATIANA DE LA FUENTE GUTIERREZ','CE - HEMATOLOGIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (70,'LIZET KARLA LIMACHI TINTAYA','CE - MAXILOFACIAL                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (71,'JORGE LOPEZ LEON','CE - MAXILOFACIAL                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (72,'HILDA COLQUE CHALLAPA','CE - MAXILOFACIAL                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (73,'BYRON ROBIN SANHUEZA MACHICAO','CE - MAXILOFACIAL                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (74,'WENDY BRENDA SOLANO SANCHEZ','CE - MAXILOFACIAL                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (75,'CE - MEDICINA INTERNA                                                                               ','',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (76,'JOSE ALEJANDRO ORTIZ ORTEGA','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (77,'OSCAR PATZI CHOQUE','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (78,'OLIVIA L RAMIREZ CANAVIRI','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (79,'AIDA SOLIZ GUZMAN','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (80,'DANIEL GUSTAVO ARANCIBIA VELASCO','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (81,'LUIS AMERICO VERA PINAYA','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (82,'JOSE ALBERTO GARNICA CHOQUE','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (83,'ALISON CHOQUE SANTOS','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (84,'JAVIER ENRIQUE MACHICADO CALLE','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (85,'JUAN CARLOS ALVAREZ SALINAS','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (86,'LIDIA GONZALES CACERES','CE - MEDICINA INTERNA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (88,'ARIEL GONZALO CONDORI CHOQUE','CE - NEFROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (89,'CARLOS A. CACERES PEREYRA','CE - NEFROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (90,'RICHARD NELSON GARCIA FUENTES','CE - NEFROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (91,'LESLIE DANIELA MARTINEZ TARIFA','CE - NEFROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (92,'PAMELA BETRIZ CARDENAS MONTENEGRO','CE - NEFROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (94,'RODOLFO FUERTES BARROVE','CE - NEUROCIRUGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (95,'JUAN PABLO GARCIA BLANCO','CE - NEUROCIRUGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (96,'RONALD DAVID AMELLER SOLANO','CE - NEUROCIRUGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (97,'ROGER SILVIO CRISPIN BONIFACIO','CE - NEUROCIRUGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (98,'NITHZE JHANSSEN PRADO NUÑEZ','CE - NEUROCIRUGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (100,'HECTOR HIBER COPA MAGNE','CE - NEUROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (101,'IGOR OLIVER QUILO ALVAREZ','CE - NEUROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (103,'PATRICIA CONDORI FLORES','CE - NUTRICION                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (104,'RAMIRO LOPEZ PACA','CE - NUTRICION                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (106,'MAURICIO C. GARCIA VALDIVIA','CE - OFTALMOLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (107,'PABLO MIGUEL ZAVALETA MERCADO','CE - OFTALMOLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (108,'RENE PANOZO JALDIN','CE - OFTALMOLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (110,'LUIS FERNANDO SACA BORDA','CE - ONCOLOGIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (111,'PAMELA ZUELEN ARAMAYO GUTIERREZ','CE - ONCOLOGIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (112,'RAUL EDMUNDO GUIBARRA TORREZ','CE - ONCOLOGIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (114,'SANTIAGO POMA CHOQUETICLLA','CE - OTORRINOLARINGOLOGIA                                                                           ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (115,'KATTY STEFANI COSSIO OQUENDO','CE - OTORRINOLARINGOLOGIA                                                                           ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (116,'MARIELA MAMANI CHAMBI','CE - OTORRINOLARINGOLOGIA                                                                           ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (118,'XIMENA ROCHA VARGAS','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (119,'ROSALIA JULIETA SANCHEZ CHOQUE','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (120,'YADIRA TORRICO ARENAS','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (121,'ALISON CHOQUE SANTOS','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (122,'MICHELLE SOFIA NINA TRONCOSO','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (123,'ELSA CALAHUANA CAUTIN','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (124,'WALDO AYALA MONTAÑO','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (125,'JOSE SATURNINO RAMOS CHOQUE','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (126,'DIEGO MOLINA TORRICO','CE - PEDIATRIA                                                                                      ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (128,'VERONICA HERRERA ALCALA','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (129,'DIEGO MOLINA TORRICO','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (130,'ROMINA SHIRLEY VILLEGAS BALDERRAMA','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (131,'ELSA CALAHUANA CAUTIN','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (132,'MARGARITA QUICAÑEZ ENRIQUEZ','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (133,'ALISON CHOQUE SANTOS','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (134,'RUTH G. MARTINEZ RONCAL','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (135,'MICHELLE SOFIA NINA TRONCOSO','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (136,'GABRIELA CAROLINA BOBARIN VARGAS','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (137,'YADIRA TORRICO ARENAS','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (138,'ZACARIAS VILLARROEL VEGA','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (139,'PATRICIA CONDARCO RAMIREZ','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (140,'GUIDO TAPIA LOPEZ','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (141,'ENRRIQUE JAVIER DORADO QUINTANILLA','CE - PEDIATRIA (CONS 1)                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (143,'FESSY KATYUSKA LARA VIRTO','CE - PSICOLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (144,'RENE RODRIGO ALIENDRE RAMIREZ','CE - PSICOLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (145,'ANA ANDREA CHOQUE CALIZAYA','CE - PSICOLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (146,'LICETH IBETH NUÑEZ RUFINO','CE - PSICOLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (147,'KATHERINE LAURA MONTOYA QUISPE','CE - PSICOLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (149,'DAVID BUSTOS CISNEROS','CE - PSIQUIATRIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (150,'ABRAHAM CHUQUIMIA MOLLO','CE - PSIQUIATRIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (151,'JOSE MARCELO ZEBALLOS GUEVARA','CE - PSIQUIATRIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (153,'ADAN GUTIERREZ HUANCA','CE - QUEMADOS                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (154,'VICTOR HUGO ROJAS GUZMAN','CE - QUEMADOS                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (156,'GUIDO TAPIA LOPEZ','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (157,'VLADIMIR JORGE PINAYA RIOS','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (158,'SACHA E. SALAS CARVALLO','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (159,'FREDDY SARAVIA CHOQUE','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (160,'GENGLER DENNIS GARCIA ARANIBAR','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (161,'JUAN CARLOS ALVAREZ SALINAS','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (162,'LUIS SOCRATES QUISPE TOLEDO','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (163,'ROBERTO REQUENA ALA','CE - TRAUMATOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (165,'JEANETTE FLORES SALVATIERRA','CE - UROLOGIA                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (166,'IBER FLORES BERRIOS','CE - UROLOGIA                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (167,'FRANKLIN OÑA BALDERRAMA','CE - UROLOGIA                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (168,'RODOLFO FABIO CLEMENTE PINTO','CE - UROLOGIA                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (169,'ANA BEATRIZ CUELLAR SALAZAR','CE - UROLOGIA                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (171,'NADEZDA MENDOZA ROMERO','CEOC - CARDIOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (172,'VELKA KATHERINA SUAZNABAR TORRICO','CEOC - CARDIOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (173,'LIZETH PEREZ MAGNE','CEOC - CARDIOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (174,'KARLA EID RODRIGUEZ','CEOC - CARDIOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (176,'CARLA  ALEJANDRA ALANDIA PACO','CEOC - CIRUGIA GENERAL                                                                              ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (177,'ABZALON LORGIO LUCAS CHOQUE','CEOC - CIRUGIA GENERAL                                                                              ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (178,'HENRY JOSE CORRALES LOPEZ','CEOC - CIRUGIA GENERAL                                                                              ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (180,'JAIME CAMACHO VALLEJOS','CEOC - DERMATOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (181,'ROBERTO REQUENA ALA','CEOC - DERMATOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (183,'LUIS RAMIRO ESCOBAR TAPIA','CEOC - ENDOCRINOLOGIA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (184,'JOSE LUIS FERNANDO LACA JIMENEZ','CEOC - ENDOCRINOLOGIA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (186,'EDSON JAVIER CHUNGARA MURUCHI','CEOC - GASTROENTEROLOGIA                                                                            ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (187,'MARIO LUIS CHALLAPA ANCALLE','CEOC - GASTROENTEROLOGIA                                                                            ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (188,'JOSE LUIS VILLEGAS YAÑEZ','CEOC - GASTROENTEROLOGIA                                                                            ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (189,'KAREN MELVA CHURATA MIRONES','CEOC - GASTROENTEROLOGIA                                                                            ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (190,'MICHAEL PEDRO BELTRAN MAMANI','CEOC - GASTROENTEROLOGIA                                                                            ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (191,'WILLIAM FLORES DIAZ','CEOC - GASTROENTEROLOGIA                                                                            ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (193,'BRESNEV MENDOZA MORA','CEOC - GERIATRIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (194,'JORGE ULISES MENDOZA MACHICADO','CEOC - GERIATRIA                                                                                    ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (196,'INES DELIA CHOQUE CRUZ','CEOC - GINECOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (197,'DAVID CAYOJA MAMANI','CEOC - GINECOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (198,'ISRAEL PEREYRA CRUZ','CEOC - GINECOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (199,'KARLA EID RODRIGUEZ','CEOC - GINECOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (200,'MICHAEL PEDRO BELTRAN MAMANI','CEOC - GINECOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (201,'ROBERTO REQUENA ALA','CEOC - GINECOLOGIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (203,'JENNY ACHA MIRANDA','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (204,'LIDIA GONZALES CACERES','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (205,'JOSE ALBERTO GARNICA CHOQUE','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (206,'CAREN MERCEDES SAUMEDIA GUZMAN','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (207,'RICARDO ROCABADO VERA','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (208,'MARLON IRO DELGADILLO CONDORI','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (209,'OLIVIA L RAMIREZ CANAVIRI','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (210,'EDSON BORYS FERNANDEZ ORTEGA','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (211,'ALEJANDRO RODY MARCA CALIZAYA','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (212,'DANIEL C. CADIZ HERBAS','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (213,'NEYSA MOYA MENDOZA','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (214,'WALDO AYALA MONTAÑO','CEOC - MEDICINA INTERNA                                                                             ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (216,'CESAR DAVID CONDORI MURGA','CEOC - NEFROLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (217,'CARLOS A. CACERES PEREYRA','CEOC - NEFROLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (219,'ELVIN ELMER LOPEZ LEDEZMA','CEOC - NEUMOLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (221,'JAIME CAMACHO VALLEJOS','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (222,'JOSE LUIS FERNANDO LACA JIMENEZ','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (223,'KARLA EID RODRIGUEZ','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (224,'LIDIA GONZALES CACERES','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (225,'OSCAR GONZALO NIGOEVIC HEREDIA','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (226,'VELKA KATHERINA SUAZNABAR TORRICO','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (227,'VENANCIO HUANCA HUANCA','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (228,'CLAUDIA  ALEJANDRA VASQUEZ PASTOR','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (229,'EDSON JAVIER CHUNGARA MURUCHI','CEOC - NEUROCIRUGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (231,'HECTOR HIBER COPA MAGNE','CEOC - NEUROLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (232,'INES DELIA CHOQUE CRUZ','CEOC - NEUROLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (234,'OSCAR GONZALO NIGOEVIC HEREDIA','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (235,'CELSO GUTIERREZ DAVALOS','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (236,'CARMEN LEDDY GUZMAN GARCIA','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (237,'DAVID CAYOJA MAMANI','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (238,'INES DELIA CHOQUE CRUZ','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (239,'JUSTO VARGAS BRUNO','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (240,'LINA CAPIO GARCIA','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (241,'MAURICIO CLEVER FLORES MORALES','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (242,'MIRIAM GOMEZ ALMANZA','CEOC - PRENATAL                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (244,'CLAUDIA  ALEJANDRA VASQUEZ PASTOR','CEOC - PSICOLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (245,'MAYA ZUAZO VARGAS','CEOC - PSICOLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (246,'ALVARO MARCELO ROCHA BALDERRAMA','CEOC - PSICOLOGIA                                                                                   ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (248,'JOSE LUIS ANTEZANA ALANDIA','CEOC - PSIQUIATRIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (249,'MAGALI JUANA GONZALES LEMUS','CEOC - PSIQUIATRIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (250,'JORGE ULISES MENDOZA MACHICADO','CEOC - PSIQUIATRIA                                                                                  ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (252,'LINA LUCANA ALCON','CEOC - REUMATOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (253,'JAIME CAMACHO VALLEJOS','CEOC - REUMATOLOGIA                                                                                 ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (255,'ROBERTO REQUENA ALA','CEOC - TRAUMATOLOGIA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (256,'LUIS MIGUEL ALBA MOLLO','CEOC - TRAUMATOLOGIA                                                                                ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (258,'VENANCIO HUANCA HUANCA','CEOC - UROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (259,'LUIS RAMIRO ESCOBAR TAPIA','CEOC - UROLOGIA                                                                                     ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (261,'ALDO GUZMAN MIRANDA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (262,'AIDA SOLIZ GUZMAN','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (263,'JAVIER ENRIQUE MACHICADO CALLE','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (264,'JORGE SEVERO CONDARCO BERRIOS','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (265,'JUAN JOSE DORADO BARRIGA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (266,'GENARO LOROÑO AJHUACHO','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (267,'LISSETH BURGOS HUALLPA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (268,'MAURICIO DURAN YAGUE','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (269,'ABEL COLQUE RAMOS','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (270,'JUSTO VARGAS BRUNO','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (271,'LUIS AMERICO VERA PINAYA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (272,'HENRY HIDALGO CHURA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (273,'OLIVIA L RAMIREZ CANAVIRI','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (274,'RENE CHINCHE CHAMBI','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (275,'ALEJANDRO RODY MARCA CALIZAYA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (276,'JUAN CARLOS ALVAREZ SALINAS','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (277,'OSCAR PATZI CHOQUE','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (278,'JOSE ALBERTO GARNICA CHOQUE','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (279,'DANIEL GUSTAVO ARANCIBIA VELASCO','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (280,'MARLON IRO DELGADILLO CONDORI','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (281,'RICARDO ROCABADO VERA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (282,'JOSE ALEJANDRO ORTIZ ORTEGA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (283,'SEVERO CONDARCO BERRIOS','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (284,'HENRY JOSE CORRALES LOPEZ','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (285,'ALISON CHOQUE SANTOS','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (286,'GUIDO TAPIA LOPEZ','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (287,'ABZALON LUCAS CHOQUE','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (288,'ALDRIN MAMANI HUANCA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (289,'EDITH GUTIERREZ ARCIENEGA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (290,'EDUARDO CALIXTO BRACAMONTE RODRIGUEZ','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (291,'ELISEO CHOQUE HUANCA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (292,'GEHOVANA BASILIA BLANCO ANTEZANA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (293,'ARMANDO DELGADO D','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (294,'JOSUE CAHUANA LIZIDRO','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (295,'ABZALON LORGIO LUCAS CHOQUE','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (296,'MARGARITA QUICAÑEZ ENRIQUEZ','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (297,'LEONARDA ARANCIBIA RAMIREZ','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (298,'TANIA GUZMAN ZEGARRA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (299,'TEODOCIA COLQUE RODRIGUEZ','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (300,'WILDSOR ARANDIA LIMACHE','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (301,'YURUSKA CESPEDES ZUBIETA','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (302,'RAUL BLANCO ROJAS','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (303,'MILENKA JAQUELINE GORDILLO FLORES','EMERGENCIA                                                                                          ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (305,'MARIA RENEE JORGE ROCHA','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (306,'MIGUEL ARELLANO ALANEZ','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (307,'EDITH ANA TRONCOSO MOLLER','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (308,'RAMIRO PADILLA TERCEROS','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (309,'CARMEN LEDDY GUZMAN GARCIA','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (310,'JOSE SATURNINO RAMOS CHOQUE','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (311,'JOSE ELMER BALDERRAMA CANEDO','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (312,'ADOLFO JORGE ESCOBAR','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (313,'JUAN UGARTE ARCE','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (314,'DEYSI MALDONADO VEGA','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (315,'HERMOGENES SEJAS GUTIERREZ','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (316,'DAVID CAYOJA MAMANI','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (317,'EDWIN ALVAREZ JORGE','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (318,'INES DELIA CHOQUE CRUZ','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (319,'JUAN JOSE DORADO BARRIGA','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (320,'ARIEL PADILLA ESCALERA','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (321,'ABZALON LORGIO LUCAS CHOQUE','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (322,'MICHAEL PEDRO BELTRAN MAMANI','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (323,'NELSON MENA CABALLERO','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (324,'OLIVIA L RAMIREZ CANAVIRI','EMERGENCIA GINECO OBSTETRICIA                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (326,'GEHOVANA BASILIA BLANCO ANTEZANA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (327,'LUIS MIGUEL VILLANUEVA MOLLO','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (328,'RUBEN LOZA LUCANA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (329,'PATRICIA CECILIA TORRICO BAUTISTA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (330,'HENRY QUISPE ASPI','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (331,'HUBER CHAVARRIA TORREZ','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (332,'JHELEN FAVIANA ARANIBAR YANA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (333,'YURI MARTINEZ MURILLO','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (334,'LUIS GUTIERREZ LOPEZ','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (335,'JAVIER ALEJANDRO MENDIZABAL CARDOZA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (336,'CAREN MERCEDES SAUMEDIA GUZMAN','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (337,'SONIA CARDOZO MARCE','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (338,'RUTH G. MARTINEZ RONCAL','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (339,'MICHELLE SOFIA NINA TRONCOSO','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (340,'NITHZE JHANSSEN PRADO NUÑEZ','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (341,'NORELYS CAROLINA SANTANA REINA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (342,'PAMELA ALTAMIRANO TORRICO','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (343,'SOLEDAD ANTEZANA .','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (344,'MARGARITA QUICAÑEZ ENRIQUEZ','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (345,'MAURICIO CLEVER FLORES MORALES','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (346,'FRANZ PETER CRUZ VASQUEZ','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (347,'HILDA COLQUE CHALLAPA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (348,'ALEJANDRO RODY MARCA CALIZAYA','EMERGENCIA OC                                                                                       ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (350,'GABRIELA CAROLINA BOBARIN VARGAS','EMERGENCIA PEDIATRICA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (351,'DIEGO MOLINA TORRICO','EMERGENCIA PEDIATRICA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (352,'YADIRA TORRICO ARENAS','EMERGENCIA PEDIATRICA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (353,'ELSA CALAHUANA CAUTIN','EMERGENCIA PEDIATRICA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (354,'ALISON CHOQUE SANTOS','EMERGENCIA PEDIATRICA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (355,'RUTH G. MARTINEZ RONCAL','EMERGENCIA PEDIATRICA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL),
	 (356,'VERONICA HERRERA ALCALA','EMERGENCIA PEDIATRICA                                                                               ',NULL,NULL,NULL,NULL,'ACTIVO',1,NULL,NULL,NULL);
