<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        // =====================================================================
        // HORMONAS CLIA — MINDRAY CL 1200i (continuación: excluye las 5 tiroideas ya insertadas)
        // =====================================================================
        DB::table('area_rangos')->insert([
            // MARCADORES TIROIDEOS
            ['area_id'=>6,'rango_nombre'=>'ANTI-PEROXIDASA (Anti TPO)','metodo'=>'CLIA','resultado'=>null,'unidad'=>'UI/ml','rango_minimo'=>null,'rango_maximo'=>9.0,'interpretacion'=>'Hasta 9,0 IU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TIROIDEOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANTI-TIROGLOBULINA (Anti Tg)','metodo'=>'CLIA','resultado'=>null,'unidad'=>'UI/ml','rango_minimo'=>null,'rango_maximo'=>4.0,'interpretacion'=>'Hasta 4,0 IU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TIROIDEOS','created_at'=>$now,'updated_at'=>$now],
            // ESTRADIOL CLIA
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Fase folicular','metodo'=>'CLIA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>20,'rango_maximo'=>138,'interpretacion'=>'20 a 138 pg/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Fase ovulatoria','metodo'=>'CLIA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>100,'rango_maximo'=>440,'interpretacion'=>'100 a 440 pg/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Fase lutea','metodo'=>'CLIA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>31,'rango_maximo'=>317,'interpretacion'=>'31 a 317 pg/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Menopausia','metodo'=>'CLIA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>null,'rango_maximo'=>25.0,'interpretacion'=>'Menor a 25,0 pg/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Hombres','metodo'=>'CLIA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>null,'rango_maximo'=>25.0,'interpretacion'=>'Menor a 25,0 pg/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // FSH CLIA
            ['area_id'=>6,'rango_nombre'=>'FSH - Fase folicular','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>3.5,'rango_maximo'=>12.5,'interpretacion'=>'3,5 a 12,5 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Fase ovulatoria','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>4.7,'rango_maximo'=>21.5,'interpretacion'=>'4,7 a 21,5 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Fase lutea','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>1.7,'rango_maximo'=>7.7,'interpretacion'=>'1,7 a 7,7 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Menopausia','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>25.8,'rango_maximo'=>134.8,'interpretacion'=>'25,8 a 134,8 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Hombres','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>1.5,'rango_maximo'=>12.4,'interpretacion'=>'1,5 a 12,4 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // LH CLIA
            ['area_id'=>6,'rango_nombre'=>'LH - Fase folicular','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>1.9,'rango_maximo'=>11.6,'interpretacion'=>'1,9 a 11,6 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Fase ovulatoria','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>12.9,'rango_maximo'=>105.2,'interpretacion'=>'12,9 a 105,2 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Fase lutea','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>0.8,'rango_maximo'=>10.5,'interpretacion'=>'0,8 a 10,5 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Menopausia','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>6.6,'rango_maximo'=>66.4,'interpretacion'=>'6,6 a 66,4 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Hombres','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>1.4,'rango_maximo'=>7.7,'interpretacion'=>'1,4 a 7,7 mIU/L','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // PROLACTINA CLIA
            ['area_id'=>6,'rango_nombre'=>'PROLACTINA (PRL) - Mujer adulta','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>3.8,'rango_maximo'=>30.7,'interpretacion'=>'3,8 a 30,7 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROLACTINA (PRL) - Postmenopáusica','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>3.2,'rango_maximo'=>24.9,'interpretacion'=>'3,2 a 24,9 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROLACTINA (PRL) - Hombre adulto','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>3.0,'rango_maximo'=>16.5,'interpretacion'=>'3,0 a 16,5 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // PROGESTERONA CLIA
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Fase folicular','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.21,'rango_maximo'=>1.72,'interpretacion'=>'0,21 a 1,72 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Fase lutea','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>3.78,'rango_maximo'=>24.60,'interpretacion'=>'3,78 a 24,60 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Postmenopáusica','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.18,'rango_maximo'=>0.83,'interpretacion'=>'0,18 a 0,83 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Hombres','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.05,'rango_maximo'=>0.92,'interpretacion'=>'0,05 a 0,92 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // TESTOSTERONA CLIA
            ['area_id'=>6,'rango_nombre'=>'TESTOSTERONA - Hombres','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>2.27,'rango_maximo'=>9.76,'interpretacion'=>'2,27 a 9,76 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TESTOSTERONA - Mujeres','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>1.23,'interpretacion'=>'≤ 1,23 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // HCG CLIA
            ['area_id'=>6,'rango_nombre'=>'HCG - 1-10 Semana','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>10,'rango_maximo'=>30,'interpretacion'=>'10 a 30 mIU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - 11-15 Semana','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>30,'rango_maximo'=>100,'interpretacion'=>'30 a 100 mIU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - 16-24 Semana','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>100,'rango_maximo'=>1000,'interpretacion'=>'100 a 1000 mIU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - 25-40 Semana','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>1000,'rango_maximo'=>10000,'interpretacion'=>'1000 a 10.000 mIU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - Mujeres no embarazadas','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>0.5,'rango_maximo'=>3.0,'interpretacion'=>'< 0,5 a 3,0 mIU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - Hombres','metodo'=>'CLIA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>0.5,'rango_maximo'=>2.2,'interpretacion'=>'< 0,5 a 2,2 mIU/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // CORTISOL Y ACTH CLIA
            ['area_id'=>6,'rango_nombre'=>'CORTISOL BASAL - Mañana (08:00 am)','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>6.4,'rango_maximo'=>22.8,'interpretacion'=>'6,4 a 22,8 ug/dl','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CORTISOL - Tarde (16:00 pm)','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>null,'rango_maximo'=>10,'interpretacion'=>'Menor a 10 ug/dl','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ADRENOCORTICOTROPINA (ACTH) - 08:00 am','metodo'=>'CLIA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>7.0,'rango_maximo'=>65.0,'interpretacion'=>'7,0 a 65,0 pg/ml','muestra'=>'PLASMA/EDTA','marca'=>'MINDRAY','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            // PTH E INSULINA CLIA
            ['area_id'=>6,'rango_nombre'=>'PARATOHORMONA (PTH)','metodo'=>'CLIA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>12.0,'rango_maximo'=>88.0,'interpretacion'=>'12,0 a 88,0 pg/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>null,'created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'INSULINA','metodo'=>'CLIA','resultado'=>null,'unidad'=>'uIU/ml','rango_minimo'=>2.2,'rango_maximo'=>25.0,'interpretacion'=>'2,2 a 25,0 uUI/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES DE DIABETES','created_at'=>$now,'updated_at'=>$now],
            // MARCADORES TUMORALES CLIA
            ['area_id'=>6,'rango_nombre'=>'CA-19-9 - Mujer','metodo'=>'CLIA','resultado'=>null,'unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>35,'interpretacion'=>'Hasta 35 U/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CA-19-9 - Varón','metodo'=>'CLIA','resultado'=>null,'unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>26,'interpretacion'=>'Hasta 26,0 U/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CA-125','metodo'=>'CLIA','resultado'=>null,'unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>35.0,'interpretacion'=>'Hasta 35,0 U/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CEA - Mujer','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>3.3,'interpretacion'=>'Mujer: 3,3 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CEA - Varón','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>5.2,'interpretacion'=>'Hasta 5,2 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'AFP','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>8.5,'interpretacion'=>'Hasta 8,5 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CA-15-3','metodo'=>'CLIA','resultado'=>null,'unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>32,'interpretacion'=>'Hasta 32 U/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            // MARCADORES PROSTÁTICOS CLIA
            ['area_id'=>6,'rango_nombre'=>'PSA TOTAL','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>4.0,'interpretacion'=>'Hasta 4,0 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES PROSTÁTICOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PSA LIBRE','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>1.0,'interpretacion'=>'Hasta 1,0 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'MARCADORES PROSTÁTICOS','created_at'=>$now,'updated_at'=>$now],
            // VITAMINA D CLIA
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Deficiente','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>20,'interpretacion'=>'Deficiente: Menor a 20 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Insuficiente','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>20,'rango_maximo'=>30,'interpretacion'=>'Insuficiente: 20 a 30 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Suficiente','metodo'=>'CLIA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>30,'rango_maximo'=>null,'interpretacion'=>'Suficiente: Mayor 30 ng/ml','muestra'=>'SUERO','marca'=>'MINDRAY','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
        ]);

        // =====================================================================
        // HORMONAS ELISA — MONOBIND / AWERENES STAT FAX 4200
        // =====================================================================
        DB::table('area_rangos')->insert([
            // PERFIL TIROIDEO ELISA
            ['area_id'=>6,'rango_nombre'=>'TIROTROPINA (TSH)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'uIU/ml','rango_minimo'=>0.28,'rango_maximo'=>6.82,'interpretacion'=>'0,28 a 6,82 uIU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TRIYODOTIRONINA (T3)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.52,'rango_maximo'=>1.85,'interpretacion'=>'0,52 a 1,85 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TIROXINA LIBRE (FT4)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/dl','rango_minimo'=>0.8,'rango_maximo'=>2.0,'interpretacion'=>'0,8 a 2,0 ng/dl','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TIROXINA TOTAL (T4)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>0.8,'rango_maximo'=>2.0,'interpretacion'=>'0,8 a 2,0 ng/dl','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TRIYODOTIRONINA LIBRE (FT3)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>1.4,'rango_maximo'=>4.2,'interpretacion'=>'1,4 a 4,2 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TIROGLOBULINA (Tg)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>3.5,'rango_maximo'=>56,'interpretacion'=>'3,5 a 56 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CALCITONINA','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>0.45,'rango_maximo'=>12.93,'interpretacion'=>'0,45 a 12,93 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TIROTROPINA NEONATAL (TSH Neo)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'uIU/ml','rango_minimo'=>0.7,'rango_maximo'=>10,'interpretacion'=>'0,7 a 10 UI/ml','muestra'=>'SANGRE DE TALÓN','marca'=>'MONOBIND','perfil'=>'PERFIL TIROIDEO','created_at'=>$now,'updated_at'=>$now],
            // MARCADORES TIROIDEOS ELISA
            ['area_id'=>6,'rango_nombre'=>'ANTI-PEROXIDASA (Anti TPO)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'UI/ml','rango_minimo'=>null,'rango_maximo'=>39.2,'interpretacion'=>'Hasta 39,2 IU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES TIROIDEOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANTI-TIROGLOBULINA (Anti Tg)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'UI/ml','rango_minimo'=>null,'rango_maximo'=>124.7,'interpretacion'=>'Hasta 124,7 IU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES TIROIDEOS','created_at'=>$now,'updated_at'=>$now],
            // HGH
            ['area_id'=>6,'rango_nombre'=>'HORMONA DE CRECIMIENTO (hGH)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'uUI/ml','rango_minimo'=>0,'rango_maximo'=>55,'interpretacion'=>'0 a 55 uUI/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // ESTRADIOL ELISA
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Fase folicular','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>9,'rango_maximo'=>175,'interpretacion'=>'9 a 175 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Fase ovulatoria','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>107,'rango_maximo'=>281,'interpretacion'=>'107 a 281 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Fase lutea','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>44,'rango_maximo'=>196,'interpretacion'=>'44 a 196 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Menopausia','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>null,'rango_maximo'=>18,'interpretacion'=>'Menor a 18,0 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ESTRADIOL (E2) - Hombres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>4,'rango_maximo'=>94,'interpretacion'=>'4,0 a 94,0 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // FSH ELISA
            ['area_id'=>6,'rango_nombre'=>'FSH - Fase folicular','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>3,'rango_maximo'=>12,'interpretacion'=>'3,0 a 12,0 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Fase ovulatoria','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>8,'rango_maximo'=>22,'interpretacion'=>'8,0 a 22,0 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Fase lutea','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>2,'rango_maximo'=>12,'interpretacion'=>'2,0 a 12,0 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Menopausia','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>35,'rango_maximo'=>151,'interpretacion'=>'35,0 a 151,0 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FSH - Hombres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>1,'rango_maximo'=>14,'interpretacion'=>'1,0 a 14,0 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // LH ELISA
            ['area_id'=>6,'rango_nombre'=>'LH - Fase folicular','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>0.5,'rango_maximo'=>10.5,'interpretacion'=>'0,5 a 10,5 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Fase ovulatoria','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>18.4,'rango_maximo'=>61.2,'interpretacion'=>'18,4 a 61,2 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Fase lutea','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>0.5,'rango_maximo'=>10.5,'interpretacion'=>'0,5 a 10,5 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Menopausia','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>8.2,'rango_maximo'=>40.8,'interpretacion'=>'8,2 a 40,8 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'LH - Hombres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/L','rango_minimo'=>0.7,'rango_maximo'=>7.4,'interpretacion'=>'0,7 a 7,4 mIU/L','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // PROLACTINA ELISA
            ['area_id'=>6,'rango_nombre'=>'PROLACTINA (PRL) - Mujer adulta','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>1.2,'rango_maximo'=>19.5,'interpretacion'=>'1,2 a 19,5 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROLACTINA (PRL) - Postmenopáusica','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>1.5,'rango_maximo'=>18.5,'interpretacion'=>'1,5 a 18,5 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROLACTINA (PRL) - Hombre adulto','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>1.8,'rango_maximo'=>17.0,'interpretacion'=>'1,8 a 17,0 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // PROGESTERONA ELISA
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Fase folicular','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.21,'rango_maximo'=>1.72,'interpretacion'=>'0,21 a 1,72 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Fase lutea','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>3.78,'rango_maximo'=>24.60,'interpretacion'=>'3,78 a 24,60 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Postmenopáusica','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.18,'rango_maximo'=>0.83,'interpretacion'=>'0,18 a 0,83 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROGESTERONA (PRG) - Hombres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.05,'rango_maximo'=>0.92,'interpretacion'=>'0,05 a 0,92 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // TESTOSTERONA ELISA
            ['area_id'=>6,'rango_nombre'=>'TESTOSTERONA TOTAL - Hombres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>2.5,'rango_maximo'=>10.0,'interpretacion'=>'2,5 a 10,0 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TESTOSTERONA TOTAL - Mujeres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.2,'rango_maximo'=>0.95,'interpretacion'=>'0,2 a 0,95 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TESTOSTERONA LIBRE - Hombres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>6.1,'rango_maximo'=>30.3,'interpretacion'=>'6,1 a 30,3 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TESTOSTERONA LIBRE - Mujeres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>0.2,'rango_maximo'=>6.1,'interpretacion'=>'0,2 a 6,1 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // HCG ELISA
            ['area_id'=>6,'rango_nombre'=>'HCG - 1-10 Semana','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>10,'rango_maximo'=>30,'interpretacion'=>'10 a 30 mIU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - 11-15 Semana','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>30,'rango_maximo'=>100,'interpretacion'=>'30 a 100 mIU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - 16-24 Semana','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>100,'rango_maximo'=>1000,'interpretacion'=>'100 a 1000 mIU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - 25-40 Semana','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>1000,'rango_maximo'=>10000,'interpretacion'=>'1000 a 10.000 mIU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - Mujeres no embarazadas','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>0.5,'rango_maximo'=>3.0,'interpretacion'=>'< 0,5 a 3,0 mIU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HCG - Hombres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'mIU/ml','rango_minimo'=>0.5,'rango_maximo'=>2.2,'interpretacion'=>'< 0,5 a 2,2 mIU/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE FERTILIDAD','created_at'=>$now,'updated_at'=>$now],
            // CORTISOL Y ACTH ELISA
            ['area_id'=>6,'rango_nombre'=>'CORTISOL BASAL - Mañana adulto','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>5,'rango_maximo'=>23,'interpretacion'=>'Adulto: 5 a 23 ug/dl','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CORTISOL BASAL - Mañana niños','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>3,'rango_maximo'=>21,'interpretacion'=>'Niños: 3 a 21 ug/dl','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CORTISOL BASAL - Mañana recién nacido','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>1,'rango_maximo'=>24,'interpretacion'=>'RN: 1 a 24 ug/dl','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CORTISOL - Tarde adulto','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>3,'rango_maximo'=>13,'interpretacion'=>'Adulto: 3 a 13 ug/dl','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CORTISOL - Tarde niños','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ug/dl','rango_minimo'=>3,'rango_maximo'=>10,'interpretacion'=>'Niños: 3 a 10 ug/dl','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ADRENOCORTICOTROPINA (ACTH) - 08:00 am','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>7.0,'rango_maximo'=>63.0,'interpretacion'=>'7,0 a 63,0 pg/ml','muestra'=>'PLASMA/EDTA','marca'=>'MONOBIND','perfil'=>'HORMONAS DE LA CORTEZA SUPRARRENAL','created_at'=>$now,'updated_at'=>$now],
            // PTH ELISA
            ['area_id'=>6,'rango_nombre'=>'PARATOHORMONA (PTH)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'pg/ml','rango_minimo'=>9.0,'rango_maximo'=>94.0,'interpretacion'=>'9,0 a 94,0 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>null,'created_at'=>$now,'updated_at'=>$now],
            // FERRITINA
            ['area_id'=>6,'rango_nombre'=>'FERRITINA (FTN) - Hombre','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>16,'rango_maximo'=>220,'interpretacion'=>'Hombre: 16 a 220 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>null,'created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'FERRITINA (FTN) - Mujeres','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>10,'rango_maximo'=>124,'interpretacion'=>'Mujeres: 10 a 124 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>null,'created_at'=>$now,'updated_at'=>$now],
            // PÉPTIDO-C E INSULINA ELISA
            ['area_id'=>6,'rango_nombre'=>'PÉPTIDO-C','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>0.7,'rango_maximo'=>1.9,'interpretacion'=>'0,7 a 1,9 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES DE DIABETES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'INSULINA - Niños','metodo'=>'ELISA','resultado'=>null,'unidad'=>'uIU/ml','rango_minimo'=>null,'rango_maximo'=>10,'interpretacion'=>'Niños: < 10 uUI/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES DE DIABETES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'INSULINA - Adultos','metodo'=>'ELISA','resultado'=>null,'unidad'=>'uIU/ml','rango_minimo'=>0.7,'rango_maximo'=>9.0,'interpretacion'=>'Adultos: 0,7 a 9,0 uUI/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES DE DIABETES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'INSULINA - Diabéticos','metodo'=>'ELISA','resultado'=>null,'unidad'=>'uIU/ml','rango_minimo'=>0.7,'rango_maximo'=>25.0,'interpretacion'=>'Diabéticos: 0,7 a 25,0 uUI/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES DE DIABETES','created_at'=>$now,'updated_at'=>$now],
            // DÍMEROS-D, PCT, TROPONINA
            ['area_id'=>6,'rango_nombre'=>'DÍMEROS-D','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>500,'interpretacion'=>'Menor a 500 ng/ml','muestra'=>'PLASMA/CITRATADO','marca'=>'MONOBIND','perfil'=>'MARCADOR DE TROMBOSIS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PROCALCITONINA (PCT)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>0.25,'interpretacion'=>'Hasta 0,25 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADOR SÉPTICO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TROPONINA-I (cTnl)','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>1.3,'interpretacion'=>'Menor a 1,3 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADOR CARDÍACO','created_at'=>$now,'updated_at'=>$now],
            // MARCADORES TUMORALES ELISA
            ['area_id'=>6,'rango_nombre'=>'CA-19-9','metodo'=>'ELISA','resultado'=>null,'unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>40.0,'interpretacion'=>'Hasta 40,0 U/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CA-125','metodo'=>'ELISA','resultado'=>null,'unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>35.0,'interpretacion'=>'Hasta 35,0 U/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CEA','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>10.0,'interpretacion'=>'Hasta 10,0 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'AFP','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>8.5,'interpretacion'=>'Hasta 8,5 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CA-15-3','metodo'=>'ELISA','resultado'=>null,'unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>37,'interpretacion'=>'Hasta 37 U/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'B-2 MICROGLOBULINA','metodo'=>'NEFELOMETRIA','resultado'=>null,'unidad'=>'ug/ml','rango_minimo'=>null,'rango_maximo'=>2.0,'interpretacion'=>'Menor a 2,0 ug/ml','muestra'=>'SUERO','marca'=>'NEPTHAR','perfil'=>'MARCADORES TUMORALES','created_at'=>$now,'updated_at'=>$now],
            // MARCADORES PROSTÁTICOS ELISA
            ['area_id'=>6,'rango_nombre'=>'PSA TOTAL','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>4.0,'interpretacion'=>'Hasta 4,0 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES PROSTÁTICOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PSA LIBRE','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>1.3,'interpretacion'=>'Hasta 1,3 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'MARCADORES PROSTÁTICOS','created_at'=>$now,'updated_at'=>$now],
            // VITAMINA D ELISA
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Deficiencia muy grave','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>5,'interpretacion'=>'Deficiencia muy grave: < 5 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Deficiencia severa','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>5,'rango_maximo'=>10,'interpretacion'=>'Deficiencia severa: 5 a 10 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Deficiencia','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>10,'rango_maximo'=>20,'interpretacion'=>'Deficiencia: 10 a 20 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Provisión subóptima','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>20,'rango_maximo'=>30,'interpretacion'=>'Provisión subóptima: 20 a 30 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Nivel óptimo','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>30,'rango_maximo'=>50,'interpretacion'=>'Nivel óptimo: 30 a 50 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Valor alto','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>50,'rango_maximo'=>70,'interpretacion'=>'Valor alto: 50 a 70 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Sobredosis','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>70,'rango_maximo'=>150,'interpretacion'=>'Sobredosis: 70 a 150 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA D - Intoxicación','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>150,'rango_maximo'=>null,'interpretacion'=>'Intoxicación: > 150 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            // VITAMINA B12 ELISA
            ['area_id'=>6,'rango_nombre'=>'VITAMINA B12 - Recién nacido','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>160,'rango_maximo'=>1300,'interpretacion'=>'RN: 160-1300 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA B12 - Adultos','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>200,'rango_maximo'=>835,'interpretacion'=>'Adultos: 200-835 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'VITAMINA B12 - Mayor de 50 años','metodo'=>'ELISA','resultado'=>null,'unidad'=>'ng/ml','rango_minimo'=>81,'rango_maximo'=>590,'interpretacion'=>'Mayor de 50 años: 81-590 pg/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'VITAMINAS','created_at'=>$now,'updated_at'=>$now],
        ]);

        // =====================================================================
        // AUTOINMUNIDAD
        // =====================================================================
        DB::table('area_rangos')->insert([
            ['area_id'=>6,'rango_nombre'=>'ANTI-CCP - Negativo','metodo'=>'ELISA','resultado'=>'NEGATIVO','unidad'=>'IU/ml','rango_minimo'=>null,'rango_maximo'=>20,'interpretacion'=>'< 20 IU/ml — NEGATIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANTI-CCP - Positivo','metodo'=>'ELISA','resultado'=>'POSITIVO','unidad'=>'IU/ml','rango_minimo'=>20,'rango_maximo'=>null,'interpretacion'=>'≥ 20 IU/ml — POSITIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANTI-DS DNA - Negativo','metodo'=>'ELISA','resultado'=>'NEGATIVO','unidad'=>'IU/ml','rango_minimo'=>null,'rango_maximo'=>100,'interpretacion'=>'< 100 IU/ml — NEGATIVO','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANTI-DS DNA - Positivo','metodo'=>'ELISA','resultado'=>'POSITIVO','unidad'=>'IU/ml','rango_minimo'=>100,'rango_maximo'=>null,'interpretacion'=>'≥ 100 IU/ml — POSITIVO','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANA - Negativo','metodo'=>'ELISA','resultado'=>'NEGATIVO','unidad'=>null,'rango_minimo'=>null,'rango_maximo'=>1.0,'interpretacion'=>'< 1,0 — NEGATIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANA - Positivo','metodo'=>'ELISA','resultado'=>'POSITIVO','unidad'=>null,'rango_minimo'=>1.2,'rango_maximo'=>null,'interpretacion'=>'≥ 1,2 — POSITIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANA - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>null,'rango_minimo'=>1.0,'rango_maximo'=>1.2,'interpretacion'=>'1,0 a 1,2 — INDETERMINADO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PERFIL ENA - Negativo','metodo'=>'ELISA','resultado'=>'NEGATIVO','unidad'=>null,'rango_minimo'=>null,'rango_maximo'=>1.0,'interpretacion'=>'< 1,0 — NEGATIVO','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PERFIL ENA - Débil positivo','metodo'=>'ELISA','resultado'=>'DÉBIL POSITIVO','unidad'=>null,'rango_minimo'=>1.0,'rango_maximo'=>2.0,'interpretacion'=>'1,0 a 2,0 — DÉBIL POSITIVO','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PERFIL ENA - Positivo','metodo'=>'ELISA','resultado'=>'POSITIVO','unidad'=>null,'rango_minimo'=>2.0,'rango_maximo'=>5.0,'interpretacion'=>'2,0 a 5,0 — POSITIVO','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'PERFIL ENA - Alto positivo','metodo'=>'ELISA','resultado'=>'ALTO POSITIVO','unidad'=>null,'rango_minimo'=>5.0,'rango_maximo'=>null,'interpretacion'=>'≥ 5,0 — ALTO POSITIVO','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANCA-C (PR3) - Negativo','metodo'=>'ELISA','resultado'=>'NEGATIVO','unidad'=>'IU/ml','rango_minimo'=>null,'rango_maximo'=>5,'interpretacion'=>'< 5 IU/ml — NEGATIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANCA-C (PR3) - Positivo','metodo'=>'ELISA','resultado'=>'POSITIVO','unidad'=>'IU/ml','rango_minimo'=>5,'rango_maximo'=>null,'interpretacion'=>'≥ 5 IU/ml — POSITIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANCA-P (MPO) - Negativo','metodo'=>'ELISA','resultado'=>'NEGATIVO','unidad'=>'IU/ml','rango_minimo'=>null,'rango_maximo'=>5,'interpretacion'=>'< 5 IU/ml — NEGATIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'ANCA-P (MPO) - Positivo','metodo'=>'ELISA','resultado'=>'POSITIVO','unidad'=>'IU/ml','rango_minimo'=>5,'rango_maximo'=>null,'interpretacion'=>'≥ 5 IU/ml — POSITIVO','muestra'=>'SUERO','marca'=>'ORGENTEC','perfil'=>'MARCADORES DE AUTOINMUNIDAD','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'C3','metodo'=>'NEFELOMETRIA','resultado'=>null,'unidad'=>'g/L','rango_minimo'=>0.9,'rango_maximo'=>1.8,'interpretacion'=>'0,9 a 1,8 g/L','muestra'=>'SUERO','marca'=>'NEPTHAR','perfil'=>'INMUNOGLOBULINAS Y COMPLEMENTO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'C4','metodo'=>'NEFELOMETRIA','resultado'=>null,'unidad'=>'g/L','rango_minimo'=>0.1,'rango_maximo'=>0.4,'interpretacion'=>'0,1 a 0,4 g/L','muestra'=>'SUERO','marca'=>'NEPTHAR','perfil'=>'INMUNOGLOBULINAS Y COMPLEMENTO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'INMUNOGLOBULINA IgA','metodo'=>'NEFELOMETRIA','resultado'=>null,'unidad'=>'g/L','rango_minimo'=>0.7,'rango_maximo'=>4.0,'interpretacion'=>'0,7 a 4,0 g/L','muestra'=>'SUERO','marca'=>'NEPTHAR','perfil'=>'INMUNOGLOBULINAS Y COMPLEMENTO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'INMUNOGLOBULINA IgG','metodo'=>'NEFELOMETRIA','resultado'=>null,'unidad'=>'g/L','rango_minimo'=>7.0,'rango_maximo'=>16.0,'interpretacion'=>'7,0 a 16,0 g/L','muestra'=>'SUERO','marca'=>'NEPTHAR','perfil'=>'INMUNOGLOBULINAS Y COMPLEMENTO','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'INMUNOGLOBULINA IgM','metodo'=>'NEFELOMETRIA','resultado'=>null,'unidad'=>'g/L','rango_minimo'=>0.4,'rango_maximo'=>2.3,'interpretacion'=>'0,4 a 2,3 g/L','muestra'=>'SUERO','marca'=>'NEPTHAR','perfil'=>'INMUNOGLOBULINAS Y COMPLEMENTO','created_at'=>$now,'updated_at'=>$now],
        ]);

        // =====================================================================
        // INFECCIOSOS
        // =====================================================================
        DB::table('area_rangos')->insert([
            // TOXOPLASMOSIS
            ['area_id'=>6,'rango_nombre'=>'TOXOPLASMOSIS IgM - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'IU/ml','rango_minimo'=>null,'rango_maximo'=>1.0,'interpretacion'=>'< 1,0 IU/ml','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TOXOPLASMOSIS IgM - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'IU/ml','rango_minimo'=>1.2,'rango_maximo'=>null,'interpretacion'=>'≥ 1,2 IU/ml','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TOXOPLASMOSIS IgM - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'IU/ml','rango_minimo'=>1.0,'rango_maximo'=>1.2,'interpretacion'=>'1,0 a 1,2 IU/ml','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TOXOPLASMOSIS IgG - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'IU/ml','rango_minimo'=>null,'rango_maximo'=>50,'interpretacion'=>'< 50 IU/ml','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'TOXOPLASMOSIS IgG - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'IU/ml','rango_minimo'=>50,'rango_maximo'=>null,'interpretacion'=>'≥ 50 IU/ml','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            // CHAGAS
            ['area_id'=>6,'rango_nombre'=>'CHAGAS ELISA - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'DO','rango_minimo'=>null,'rango_maximo'=>null,'interpretacion'=>'DO < 10%+CuttOff','muestra'=>'SUERO','marca'=>'LEMOS','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CHAGAS ELISA - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'DO','rango_minimo'=>null,'rango_maximo'=>null,'interpretacion'=>'DO > 10%-CuttOff','muestra'=>'SUERO','marca'=>'LEMOS','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CHAGAS HAI - No reactivo','metodo'=>'HAI','resultado'=>'NO REACTIVO','unidad'=>'Dilución','rango_minimo'=>null,'rango_maximo'=>8,'interpretacion'=>'Hasta Dilución 8','muestra'=>'SUERO','marca'=>'LEMOS','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            // RUBÉOLA
            ['area_id'=>6,'rango_nombre'=>'RUBÉOLA IgM - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'RV','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9 RV','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'RUBÉOLA IgM - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'RV','rango_minimo'=>10,'rango_maximo'=>null,'interpretacion'=>'≥ 10 RV','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'RUBÉOLA IgM - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'RV','rango_minimo'=>9,'rango_maximo'=>10,'interpretacion'=>'9 a 10 RV','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            // CMV
            ['area_id'=>6,'rango_nombre'=>'CMV IgM - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CMV IgM - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CMV IgM - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CMV IgG - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CMV IgG - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CMV IgG - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            // HERPES (HSV)
            ['area_id'=>6,'rango_nombre'=>'HERPES (HSV) IgM Tipo 2 - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HERPES (HSV) IgM Tipo 2 - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HERPES (HSV) IgM Tipo 2 - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HERPES (HSV) IgG Tipo 2 - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HERPES (HSV) IgG Tipo 2 - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HERPES (HSV) IgG Tipo 2 - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            // EPSTEIN-BARR
            ['area_id'=>6,'rango_nombre'=>'EPSTEIN-BARR (EBV) IgM - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'NTU','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9 NTU','muestra'=>'SUERO','marca'=>'NOVALISA','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'EPSTEIN-BARR (EBV) IgM - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'NTU','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11 NTU','muestra'=>'SUERO','marca'=>'NOVALISA','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'EPSTEIN-BARR (EBV) IgM - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'NTU','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11 NTU','muestra'=>'SUERO','marca'=>'NOVALISA','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'EPSTEIN-BARR (EBV) IgG - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'NTU','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9 NTU','muestra'=>'SUERO','marca'=>'NOVALISA','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'EPSTEIN-BARR (EBV) IgG - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'NTU','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11 NTU','muestra'=>'SUERO','marca'=>'NOVALISA','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'EPSTEIN-BARR (EBV) IgG - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'NTU','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11 NTU','muestra'=>'SUERO','marca'=>'NOVALISA','perfil'=>'TORCH','created_at'=>$now,'updated_at'=>$now],
            // CHLAMYDIA
            ['area_id'=>6,'rango_nombre'=>'CHLAMYDIA TRACHOMATIS IgM - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CHLAMYDIA TRACHOMATIS IgM - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CHLAMYDIA TRACHOMATIS IgM - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CHLAMYDIA TRACHOMATIS IgG - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CHLAMYDIA TRACHOMATIS IgG - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'CHLAMYDIA TRACHOMATIS IgG - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            // SÍFILIS
            ['area_id'=>6,'rango_nombre'=>'SYPHILIS (SÍFILIS) Ab - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>9,'interpretacion'=>'< 9','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'SYPHILIS (SÍFILIS) Ab - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>11,'rango_maximo'=>null,'interpretacion'=>'≥ 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'SYPHILIS (SÍFILIS) Ab - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>9,'rango_maximo'=>11,'interpretacion'=>'9 a 11','muestra'=>'SUERO','marca'=>'VIRCELL','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            // HIDATIDOSIS
            ['area_id'=>6,'rango_nombre'=>'HIDATIDOSIS (Echinococcus) IgG - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>0.8,'interpretacion'=>'≤ 0,8','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HIDATIDOSIS (Echinococcus) IgG - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>1.1,'rango_maximo'=>null,'interpretacion'=>'≥ 1,1','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HIDATIDOSIS (Echinococcus) IgG - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>0.8,'rango_maximo'=>1.1,'interpretacion'=>'0,8 a 1,1','muestra'=>'SUERO','marca'=>'EUROINMUN','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            // H. PYLORI
            ['area_id'=>6,'rango_nombre'=>'H. PYLORI IgM','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>40,'interpretacion'=>'Hasta 40 U/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'H. PYLORI IgG','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'U/ml','rango_minimo'=>null,'rango_maximo'=>20,'interpretacion'=>'Hasta 20 U/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'H. PYLORI Ag - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'ng/ml','rango_minimo'=>null,'rango_maximo'=>15,'interpretacion'=>'≤ 15 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'H. PYLORI Ag - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'ng/ml','rango_minimo'=>20,'rango_maximo'=>null,'interpretacion'=>'≥ 20 ng/ml','muestra'=>'SUERO','marca'=>'MONOBIND','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            // HEPATITIS
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS A (HAV IgM) - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>1.0,'interpretacion'=>'< 1,0','muestra'=>'SUERO','marca'=>'RECOMBILISA','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS A (HAV IgM) - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>1.0,'rango_maximo'=>null,'interpretacion'=>'≥ 1,0','muestra'=>'SUERO','marca'=>'RECOMBILISA','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS B (HBsAg) ELISA - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>0.9,'interpretacion'=>'< 0,9','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS B (HBsAg) ELISA - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>1.1,'rango_maximo'=>null,'interpretacion'=>'≥ 1,1','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS B (HBsAg) ELISA - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>0.9,'rango_maximo'=>1.1,'interpretacion'=>'0,9 a 1,1','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS B (HBcAb) - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>0.9,'interpretacion'=>'< 0,9','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS B (HBcAb) - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>1.1,'rango_maximo'=>null,'interpretacion'=>'≥ 1,1','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS B (HBcAb) - Indeterminado','metodo'=>'ELISA','resultado'=>'INDETERMINADO','unidad'=>'V.I.','rango_minimo'=>0.9,'rango_maximo'=>1.1,'interpretacion'=>'0,9 a 1,1','muestra'=>'SUERO','marca'=>'DIAPRO','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS C (HCV Ab) ELISA - No reactivo','metodo'=>'ELISA','resultado'=>'NO REACTIVO','unidad'=>'V.I.','rango_minimo'=>null,'rango_maximo'=>1.0,'interpretacion'=>'< 1,0','muestra'=>'SUERO','marca'=>'RECOMBILISA','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS C (HCV Ab) ELISA - Reactivo','metodo'=>'ELISA','resultado'=>'REACTIVO','unidad'=>'V.I.','rango_minimo'=>1.0,'rango_maximo'=>null,'interpretacion'=>'≥ 1,0','muestra'=>'SUERO','marca'=>'RECOMBILISA','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS B (HBsAg) CROMATOGRAFIA','metodo'=>'CROMATOGRAFIA','resultado'=>'NO REACTIVO','unidad'=>null,'rango_minimo'=>null,'rango_maximo'=>null,'interpretacion'=>'NO REACTIVO','muestra'=>'SUERO','marca'=>'ABOOT','perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
            ['area_id'=>6,'rango_nombre'=>'HEPATITIS C (HCV Ab) CROMATOGRAFIA','metodo'=>'CROMATOGRAFIA','resultado'=>'NO REACTIVO','unidad'=>null,'rango_minimo'=>null,'rango_maximo'=>null,'interpretacion'=>'NO REACTIVO','muestra'=>'SUERO','marca'=>null,'perfil'=>'INFECCIOSOS','created_at'=>$now,'updated_at'=>$now],
        ]);
    }

    public function down(): void
    {
        // Elimina todos los registros de area_id=6 insertados por esta migración
        // (los 5 de PERFIL TIROIDEO CLIA pertenecen a la migración anterior)
        DB::table('area_rangos')
            ->where('area_id', 6)
            ->whereNotIn('rango_nombre', [
                'TIROTROPINA (TSH)', 'TRIYODOTIRONINA (T3)',
                'TIROXINA LIBRE (FT4)', 'TIROXINA TOTAL (T4)', 'TIROGLOBULINA (Tg)',
            ])
            ->where('metodo', '!=', 'CLIA')
            ->orWhere(function ($q) {
                $q->where('area_id', 6)
                  ->whereIn('rango_nombre', [
                      'ANTI-PEROXIDASA (Anti TPO)', 'ANTI-TIROGLOBULINA (Anti Tg)',
                      'ESTRADIOL (E2) - Fase folicular', 'ESTRADIOL (E2) - Fase ovulatoria',
                      'ESTRADIOL (E2) - Fase lutea', 'ESTRADIOL (E2) - Menopausia',
                      'ESTRADIOL (E2) - Hombres',
                      'FSH - Fase folicular', 'FSH - Fase ovulatoria', 'FSH - Fase lutea',
                      'FSH - Menopausia', 'FSH - Hombres',
                      'LH - Fase folicular', 'LH - Fase ovulatoria', 'LH - Fase lutea',
                      'LH - Menopausia', 'LH - Hombres',
                      'PROLACTINA (PRL) - Mujer adulta', 'PROLACTINA (PRL) - Postmenopáusica',
                      'PROLACTINA (PRL) - Hombre adulto',
                      'PROGESTERONA (PRG) - Fase folicular', 'PROGESTERONA (PRG) - Fase lutea',
                      'PROGESTERONA (PRG) - Postmenopáusica', 'PROGESTERONA (PRG) - Hombres',
                      'TESTOSTERONA - Hombres', 'TESTOSTERONA - Mujeres',
                      'HCG - 1-10 Semana', 'HCG - 11-15 Semana', 'HCG - 16-24 Semana',
                      'HCG - 25-40 Semana', 'HCG - Mujeres no embarazadas', 'HCG - Hombres',
                      'CORTISOL BASAL - Mañana (08:00 am)', 'CORTISOL - Tarde (16:00 pm)',
                      'ADRENOCORTICOTROPINA (ACTH) - 08:00 am', 'PARATOHORMONA (PTH)',
                      'INSULINA', 'CA-19-9 - Mujer', 'CA-19-9 - Varón',
                      'CA-125', 'CEA - Mujer', 'CEA - Varón', 'AFP', 'CA-15-3',
                      'PSA TOTAL', 'PSA LIBRE',
                      'VITAMINA D - Deficiente', 'VITAMINA D - Insuficiente', 'VITAMINA D - Suficiente',
                  ])
                  ->where('metodo', 'CLIA');
            })
            ->delete();
    }
};
