<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        $categorias = [
            'INTERNACION' => [
                ['1', 'Sala de internacion privada por día', 250.00],
                ['2', 'Sala de internacion comun por día', 200.00],
                ['3', 'Enfermera de cabecera por turno de 6 hrs.', 160.00],
                ['4', 'Reposición de material de enfermería por día', 50.00],
                ['5', 'Seguimiento medico de guardia (dia)', 50.00],
                ['6', 'Derecho de Admisión', 50.00],
            ],
            'USO DE QUIROFANO' => [
                ['1', 'Cirugía Mayor 2 hrs', 1500.00],
                ['2', 'Cirugía mediana 2 hrs.', 1200.00],
                ['3', 'Cirugia minima 2 hrs', 800.00],
                ['4', 'Instrumentacion por cirugia', 300.00],
                ['5', 'Circulante por cirujia', 200.00],
                ['6', 'Superado las dos horas de quirofano por hora adicional', 1000.00],
                ['7', 'Uso de equipo laparoscopia', 1200.00],
                ['8', 'Uso de arco en "C"', 1200.00],
            ],
            'SALAS DE PROCEDIMIENTOS' => [
                ['1', 'Sala de partos', 500.00],
                ['2', 'Sala de legrado', 500.00],
                ['3', 'Sala de procedimientos medicos', 500.00],
                ['4', 'Sala de yeso', 100.00],
            ],
            'OXIGENO TERAPIA' => [
                ['2', 'Nebulizaciones por sesión', 40.00],
                ['3', 'Oxigeno por hora (1 a 3 libras)', 40.00],
            ],
            'SERVICIO MEDICO' => [
                ['1', 'Uso de consultorio', 100.00],
                ['2', 'Consulta en domicilio', 150.00],
                ['3', 'Consulta General', 60.00],
                ['4', 'Consulta Emergencia', 70.00],
                ['5', 'Consulta externa Medico General', 120.00],
                ['6', 'Colocacion de yeso', 100.00],
                ['7', 'Retiro de yeso', 100.00],
                ['8', 'Sala de yeso', 80.00],
                ['9', 'Retiro de puntos', 15.00],
                ['10', 'Caja de curacion grande', 100.00],
                ['11', 'Caja de curacion mediana', 80.00],
                ['12', 'Caja de curacion pequeña', 50.00],
                ['13', 'Sutura por punto supradermicos', 15.00],
                ['14', 'Sutura por punto intradermicos', 30.00],
                ['15', 'Lavado de Oido', 100.00],
                ['16', 'Lavado Ocular', 100.00],
                ['17', 'Procedimientos medicos', 150.00],
            ],
            'ESTUDIOS DIAGNOSTICOS' => [
                ['-', 'Electrocardiograma', 350.00],
                ['-', 'Electroencefalograma', 400.00],
            ],
            'SERVICIO DE ENFERMERIA' => [
                ['1', 'Inyectable intramuscular s/ jeringa', 5.00],
                ['2', 'Inyectable intravenoso s/ jeringa', 10.00],
                ['3', 'Inyectable a domicilio', 30.00],
                ['4', 'Venoclisis 2 hrs de internacion', 50.00],
                ['5', 'Colocacion de enema', 50.00],
            ],
            'U.T.I. ADULTOS' => [
                ['1', 'Internacion por dia', 800.00],
                ['2', 'Uso de monitor por dia', 300.00],
                ['3', 'Uso de bomba de infusion por dia', 300.00],
                ['4', 'Uso de ventilador mecanico por dia', 300.00],
                ['5', 'Glicemia capilar por toma', 20.00],
                ['6', 'Oxigeno por hora', 30.00],
                ['7', 'Turno de enfermeria de 6 horas', 150.00],
                ['8', 'Reposición de material de enfermería por día', 30.00],
            ],
            'NEONATOLOGIA' => [
                ['1', 'Incubadora por dia', 300.00],
                ['2', 'Fototerapia por hora', 35.00],
                ['3', 'Octofototeria por hora', 35.00],
                ['4', 'Cuna por dia', 150.00],
                ['5', 'Tubo de oxigeno', 200.00],
                ['6', 'Turno de enfermeria de 6 horas', 150.00],
            ],
            'RAYOS X SIN INFORME' => [
                ['1', 'Cráneo AP- LAT.', 150.00],
                ['2', 'Tórax AP', 150.00],
                ['3', 'Tórax LAT', 150.00],
                ['4', 'Abdomen Simple o de pie', 150.00],
                ['5', 'Pelvis o Cadera (adulto)', 150.00],
                ['6', 'Pelvis entrada y salida (adulto)', 300.00],
                ['7', 'Pelvis Obturatriz - Alar', 150.00],
                ['8', 'Pelvis o Cadera (niño)', 130.00],
                ['9', 'Columna cervical AP-LAT.', 150.00],
                ['10', 'Columna Cervical dinámicas', 150.00],
                ['11', 'Columna Dorsal AP- LAT.', 150.00],
                ['12', 'Columna Lumbar AP-LAT.', 150.00],
                ['13', 'Columna sacro cóccix AP- LAT.', 150.00],
                ['14', 'Fémur AP-LAT', 150.00],
                ['15', 'Pierna AP-LAT', 150.00],
                ['16', 'Brazo o Humero AP- LAT', 150.00],
                ['17', 'Antebrazo AP- LAT', 150.00],
                ['18', 'Rodilla AP-LAT', 120.00],
                ['19', 'Pie AP-OBL LAT', 100.00],
                ['20', 'Mano PA-OBL LAT', 100.00],
                ['21', 'Tobillo AP-LAT', 100.00],
                ['22', 'Codo AP-LAT', 100.00],
                ['23', 'Clavicula - Hombro - Escapula (cada miembro)', 150.00],
                ['24', 'Huesos propios de la Nariz - HPN', 150.00],
                ['25/26', 'Senos Paranasales MNP-FNP Watters - Cadwell', 150.00],
                ['27', 'Test de Farrell (2 años)', 300.00],
                ['28', 'Histerosalpingografia', 200.00],
                ['29', 'Colangiografia', 200.00],
                ['30', 'Maxilar Inferior frente', 150.00],
                ['31', 'Hirtz-towne o base de cráneo', 150.00],
                ['32', 'Hemitorax o Parrilla costal', 150.00],
                ['33', 'Axiales de rotulas 60, 45, 30', 100.00],
                ['34', 'Calcáneo Axial - LAT', 100.00],
                ['35', 'Rayos X en horario de emergencia', 50.00],
                ['36', 'Informe de rayos X', 50.00],
            ],
            'RAYOS X CONTRASTADOS' => [
                ['1', 'Transito intestinal', 350.00],
                ['2', 'Colon por enema', 350.00],
                ['3', 'Urograma excretor', 400.00],
                ['4', 'Histero-salpingografia', 400.00],
                ['5', 'Trago de bario', 200.00],
                ['6', 'Eso-fagografia', 400.00],
                ['7', 'Uretro-cistografia', 400.00],
            ],
            'TOMOGRAFIA EN C.D.' => [
                ['1', 'Abdomen y pelvis con contraste', 1000.00],
                ['2', 'Abdomen y pelvis sin contraste', 900.00],
                ['3', 'Abdomen con contraste', 900.00],
                ['4', 'Abdomen simple', 800.00],
                ['5', 'Tórax con contraste', 700.00],
                ['6', 'Tórax sin contraste', 600.00],
                ['7', 'Pelvis con contraste', 700.00],
                ['8', 'Pelvis sin contraste', 600.00],
                ['9', 'Columna cervical', 700.00],
                ['10', 'Columna Dorsal completa', 1100.00],
                ['11', 'Columna Lumbar completa', 700.00],
                ['12', 'Columna Sacro-coxis', 800.00],
                ['13', 'Angiotac por area (craneo, vasos de cuello, aorta, pulmonar, etc.) cada miembro', 1100.00],
                ['14', 'Columna total con contraste técnica Raquídea', 1900.00],
                ['15', 'Columna total sin contraste', 1900.00],
                ['16', 'Cráneo con contraste', 700.00],
                ['17', 'Cráneo Simple - con ventana ósea', 400.00],
                ['18', 'Cráneo 3D', 300.00],
                ['19', 'Urotac', 450.00],
                ['20', 'Cuello con contraste', 700.00],
                ['21', 'Cuello sin contraste', 700.00],
                ['22', 'Hombro-codo-muñeca-mano-rodilla-tobillo-pie + 3D (cada miembro)', 600.00],
                ['23', 'Macizo Facial con contraste', 600.00],
                ['24', 'Macizo Facial sin contraste', 800.00],
                ['25', 'Macizo Facial 3-D', 700.00],
                ['26', 'Oidos peñascos con contraste', 800.00],
                ['27', 'Oidos peñascos sin contraste', 800.00],
                ['28', 'Orbitas con contraste', 700.00],
                ['29', 'Orbitas sin contraste', 800.00],
                ['30', 'Perfusión Cerebral por tomografía', 900.00],
                ['31', 'PIELOTAC sin contraste (Abdomen simple)', 800.00],
                ['32', 'Pierna-fémur-antebrazo-humero + 3D (cada miembro)', 700.00],
                ['33', 'Senos paranasales con contraste', 600.00],
                ['34', 'Senos paranasales sin contraste', 500.00],
                ['35', 'Silla turca - Hipófisis con contraste', 450.00],
                ['36', 'Silla turca - Hipófisis sin contraste', 350.00],
                ['37', 'Tomografia en horario de emergencia por estudio', 50.00],
            ],
            'LABORATORIOS' => [
                ['2', 'Gasometria arterial (Hematologia)', 400.00],
                ['3', 'Hemograma completo', 40.00],
                ['4', 'Grupo sanguineo y factor', 20.00],
                ['5', 'Recuento de plaquetas', 25.00],
                ['6', 'Recuento de reticulocitos', 25.00],
                ['7', 'Hemoglobina glicosilada', 100.00],
                ['8', 'Hemoglobina + hematocrito', 30.00],
                ['9', 'Leucograma', 15.00],
                ['10', 'Tiempo de sangria y coagulacion', 15.00],
                ['11', 'Tiempo de protrombina + inr actividad (Coagulograma)', 30.00],
                ['12', 'Glucosa (Quimica sanguinea)', 30.00],
                ['13', 'Glucosa posprandial', 30.00],
                ['14', 'Hb. Glicosilada', 70.00],
                ['55', 'Coproparasitologico seriado (3 MUE)', 40.00],
                ['56', 'Grasa fecal y moco fecal examen en fresco', 20.00],
                ['57', 'Gran depo (ex. Fresco y tincion gram)', 40.00],
                ['59', 'Tincion gram (Esputo, Heces, Secreción vaginal) - Bacteriologia', 20.00],
                ['60', 'Examen en fresco', 20.00],
                ['62', 'Examen general de orina (Uroanalisis)', 20.00],
                ['63', 'Laboratorio en horario de emergencia', 50.00],
            ],
            'ECOGRAFIA' => [
                ['1', 'Abdominal - Hepatobilio pancreatico', 150.00],
                ['2', 'Pelvica', 150.00],
                ['3', 'Prostatico', 200.00],
                ['4', 'Renal bilateral', 150.00],
                ['5', 'Vesical', 150.00],
                ['6', 'Vias urinarias', 210.00],
                ['7', 'Inguinal bilateral', 180.00],
                ['8', 'Testicular', 200.00],
                ['9', 'Ocular', 250.00],
                ['10', 'Doppler por miembro', 250.00],
                ['11', 'Ginecologica (via abdominal)', 140.00],
                ['12', 'Transvaginal', 140.00],
                ['13', 'Doppler transvaginal con rastreo subperitoneal (endometriosis)', 250.00],
                ['14', 'Transperineal (piso vesical)', 250.00],
                ['15', 'Mamaria bilateral', 200.00],
                ['16', 'Obstetrica', 140.00],
                ['17', 'Obstetrica 3D', 300.00],
                ['18', 'Obstetrica doppler', 300.00],
                ['18', 'Perfil Biofisico', 100.00],
                ['18', 'Partes blandas', 180.00],
                ['18', 'Musculo esqueletico', 200.00],
                ['21', 'Transfontanelar', 250.00],
                ['22', 'Displacia en cadera (bebes)', 250.00],
                ['23', 'Canal medular (lumbo sacro bebes)', 250.00],
                ['24', 'Tiroidea', 180.00],
                ['25', 'Toraxica - Pleural', 150.00],
                ['26', 'Glandulas salivales', 200.00],
                ['27', 'Cuello', 180.00],
                ['28', 'Ginecologica con conteo folicular', 150.00],
                ['29', 'Obstetrica tn-hn semana 11/14 (genetica)', 240.00],
                ['30', 'Obstetrica estructurada morfologica', 300.00],
                ['31', 'Obstetrica cervicometria transvaginal', 150.00],
                ['32', 'Ecografia en horario de emergencia', 100.00],
            ],
            'AMBULANCIA' => [
                ['1', 'Dentro radio urbano', 150.00],
                ['2', 'Fuera del radio urbano', 200.00],
            ],
        ];

        foreach ($categorias as $nombreCategoria => $items) {
            $tipoProductoId = DB::table('tipo_productos')->where('nombre', $nombreCategoria)->value('id');
            if (!$tipoProductoId) {
                $tipoProductoId = DB::table('tipo_productos')->insertGetId([
                    'nombre'     => $nombreCategoria,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }

            foreach ($items as [$codigo, $nombre, $precio]) {
                DB::table('productos')->insert([
                    'codigo'           => $codigo,
                    'nombre'           => mb_strtoupper($nombre),
                    'descripcion'      => null,
                    'marca'            => null,
                    'fabricante_id'    => null,
                    'unidad_id'        => null,
                    'tipo'             => 'FARMACIA',
                    'tipo_producto_id' => $tipoProductoId,
                    'precio'           => $precio,
                    'created_at'       => $now,
                    'updated_at'       => $now,
                ]);
            }
        }
    }

    public function down(): void
    {
        // Data seed only; not reversible.
    }
};
